version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imagefootage-app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL="w00884wscgkwwso4044sscow.18.218.166.222.sslip.io"
      - DB_CONNECTION=mysql
      - DB_HOST="18.218.166.222"           # external MySQL host/IP
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE="imagefootage"
      - DB_USERNAME="mysql"
      - DB_PASSWORD="Fp1TCqO9LkZHD66EEFCa4b9cmonxgbc580zfHBnMqM59FzNx4dy8yLes2n4gkl9c"
      - SESSION_DRIVER=file
      - CACHE_DRIVER=file
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - imagefootage-network

networks:
  imagefootage-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local